/* Generated By:JavaCC: Do not edit this line. SimplePathParserConstants.java */
package org.pennyledger.form.path.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimplePathParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LAST = 3;
  /** RegularExpression Id. */
  int SLASHSLASH = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int NAME = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"last\"",
    "\"//\"",
    "<NUMBER>",
    "<DIGIT>",
    "<LETTER>",
    "<NAME>",
    "\"/\"",
    "\"*\"",
    "\"[\"",
    "\"]\"",
  };

}
