drop table dividendVoucher;

create table dividendVoucher (
  id integer generated by default as identity not null primary key,
  version timestamp default current timestamp not null,
  
  eventDate date not null,
  distributionNo integer not null,
  companyYear integer not null,
  accountingYearEnd date not null,
  dividendType varchar(10) not null,
  dividendPerShare decimal(10,4) not null,
  shares integer not null,
  dividendPayment decimal(10,2) not null,
  taxCredit decimal(10,2) not null,
  totalDividend decimal(10,2) not null,

  name varchar(30) not null,
  address varchar(30) not null,
  town varchar(30) not null,
  postcode varchar(12) not null,
  shareholderCode varchar(4) not null
);

select 'Record count: ', count(*) from DividendVoucher;
