drop table document;

create table document (
  id integer generated by default as identity not null primary key,
  version timestamp default current timestamp not null,
  class varchar(255) not null,
  data blob not null,
  constraint document_uc1 unique (class)
);
